name: Manual Trigger

on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Choose Environment"
                default: "staging"
                required: true
                type: choice
                options:
                    - staging
                    - production

jobs:
    stage:
        runs-on: ubuntu-latest
        steps:
            - name: print input
              run: echo "Environment selected${{ github.event.inputs.environment }}"