name: Pull request check

on:
  pull_request:
    branches: [main]
    types: [opened] 
  schedule:
    - cron: '0 0 * * *'

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: branch name
        run: echo "branch is ${{ github.ref_name }}"

      - name: hey Alfaiz
        run: echo "Hey Alfaiz you are doing great, keep it up!"
